Repository SOPT-all/36-COLLABORATION-WEB-KYOBOBOOK, pull requests merged in 2025-05, with the labels that each got.

#2 [chore] 초기 환경 세팅
  .gitignore
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 💬 Chore, 🌼 새봄

#4 [chore] develop 브랜치를 default로 변경
  .gitignore
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 💬 Chore, 🌵 수정

#5 [chore] PR 템플릿 생성 및 query-client 파일 분리
  .github/PULL_REQUEST_TEMPLATE.md
  src/App.tsx
  src/main.tsx
  src/utils/query-client.ts
Labels: 💬 Chore, 🌵 수정

#7 [chore] 폴더구조 세팅
  .github/ISSUE_TEMPLATE/✨이슈-템플릿.md
  .github/PULL_REQUEST_TEMPLATE.md
  public/svg/.gitkeep
  src/apis/.gitkeep
  src/assets/img/.gitkeep
  src/assets/svg/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/hooks/.gitkeep
  src/pages/Home/.gitkeep
  src/pages/HomeBest/.gitkeep
  src/pages/HomeBestDetail/.gitkeep
  src/pages/HomeBestDetailCart/.gitkeep
  src/routes/.gitkeep
  src/styles/.gitkeep
  src/types/.gitkeep
Labels: 💬 Chore, 🌵 수정

#11 [chore] 라우팅 세팅 및 절대 경로 설정
  src/App.tsx
  src/pages/Home/Home.tsx
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/routes/Router.tsx
  src/routes/pageRoutes.tsx
  src/routes/routePath.ts
  tsconfig.app.json
  vite.config.ts
Labels: 💬 Chore, 🌟 혜성

#10 [chore] 기본 스타일 시스템 세팅
  src/App.tsx
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/routes/pageRoutes.tsx
  src/styles/GlobalStyle.tsx
  src/styles/fonts.ts
  src/styles/theme.ts
  tsconfig.app.json
  vite.config.ts
Labels: 🎨 Style, 💬 Chore, ☃️ 승우

#15 [chore] CODEOWNERS 설정 및 CI/CD 빌드 관련 파일 추가 및 husky 설정
  .github/CODEOWNERS
  .github/workflows/ci-cd.yml
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.cjs
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/main.tsx
  src/pages/Home/.gitkeep
  src/pages/Home/Home.tsx
  src/pages/HomeBest/.gitkeep
  src/pages/HomeBestDetail/.gitkeep
  src/pages/HomeBestDetailCart/.gitkeep
  src/routes/.gitkeep
  src/routes/Router.tsx
  src/styles/.gitkeep
  src/styles/theme.ts
  src/types/IconType.ts
Labels: 💬 Chore, 🌵 수정, 🔗 CI/CD

#19 [chore] cicd 일부 수정 및 기존 코드 화살표 함수로 변경
  .github/CODEOWNERS
  .github/workflows/ci-cd.yml
  src/App.tsx
  src/assets/icons/Example.tsx
  src/components/Icon.tsx
  src/routes/Router.tsx
Labels: 💬 Chore, 🌵 수정

#20 [feat] Card, Divider 공통 컴포넌트 제작
  .husky/commit-msg
  .husky/pre-commit
  src/assets/img/sample.png
  src/components/Card/Card.styles.ts
  src/components/Card/Card.tsx
  src/components/Divider/Divider.style.ts
  src/components/Divider/Divider.tsx
  src/components/Icon.tsx
  src/pages/Home/Home.tsx
  src/styles/textStyles.ts
  src/types/cardTypes.ts
  src/types/iconTypes.ts
Labels: 🛠️ Feature, 🌼 새봄

#30 [feat] 컴포넌트: StarRating 컴포넌트 제작
  src/assets/icons/svg/ic_star.svg
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/StarRating/StarRating.style.ts
  src/pages/HomeBestDetail/StarRating/StarRating.tsx
Labels: 🛠️ Feature, 🌼 새봄

#26 [feat] 공통 컴포넌트: 좌우 스크롤 구현
  src/components/HorizontalScroll/HorizontalScroll.style.ts
  src/components/HorizontalScroll/HorizontalScroll.tsx
Labels: 🛠️ Feature, 🌵 수정

#24 [feat] 공통 컴포넌트: 푸터, 헤더 제작
  src/assets/icons/index.ts
  src/assets/icons/svg/ic_circle_down.svg
  src/assets/icons/svg/ic_dot.svg
  src/assets/icons/svg/ic_header_logo.svg
  src/assets/icons/svg/ic_kyobo_logo.svg
  src/assets/icons/svg/ic_nav_ebook.svg
  src/assets/icons/svg/ic_nav_hottracks.svg
  src/assets/icons/svg/ic_nav_logo_background.svg
  src/assets/icons/svg/ic_nav_sam.svg
  src/components/Footer/ButtonList/ButtonList.style.ts
  src/components/Footer/ButtonList/ButtonList.tsx
  src/components/Footer/Dropdown/Dropdown.style.ts
  src/components/Footer/Dropdown/Dropdown.tsx
  src/components/Footer/Footer.constants.ts
  src/components/Footer/Footer.style.ts
  src/components/Footer/Footer.tsx
  src/components/HorizontalScroll/HorizontalScroll.style.ts
  src/components/MainHeader/MainHeader.style.ts
  src/components/MainHeader/MainHeader.tsx
  src/components/MainHeader/MainHeaderTab.constants.tsx
  src/components/MainHeader/MainHeaderTab/MainHeaderTab.style.ts
  src/components/MainHeader/MainHeaderTab/MainHeaderTab.tsx
  src/pages/Home/Home.tsx
  src/pages/HomeBest/HomeBest.tsx
Labels: 🛠️ Feature, 🌵 수정

#32 [feat] 컴포넌트: EmotionBar 컴포넌트 제작
  src/pages/HomeBestDetail/EmotionBar/EmotionBar.style.ts
  src/pages/HomeBestDetail/EmotionBar/EmotionBar.tsx
  src/pages/HomeBestDetail/EmotionBar/ReviewData.ts
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/RatingBar/RatingBar.style.ts
  src/pages/HomeBestDetail/RatingBar/RatingBar.tsx
Labels: 🛠️ Feature, 🌼 새봄

#41 [feat] RatingBar 컴포넌트
  src/pages/HomeBestDetail/EmotionBar/EmotionBar.style.ts
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/RatingBar/RatingBar.style.ts
  src/pages/HomeBestDetail/RatingBar/RatingBar.tsx
  src/pages/HomeBestDetail/StarRating/StarRating.tsx
Labels: 🛠️ Feature, 🌼 새봄

#39 [feat] homebest페이지의 bookitem
  src/assets/icons/svg/ic_wish.svg
  src/components/Footer/ButtonList/ButtonList.style.ts
  src/components/Footer/ButtonList/ButtonList.tsx
  src/components/Footer/Dropdown/Dropdown.style.ts
  src/components/Footer/Dropdown/Dropdown.tsx
  src/components/Footer/Footer.style.ts
  src/components/Footer/Footer.tsx
  src/components/MainHeader/MainHeader.style.ts
  src/components/MainHeader/MainHeader.tsx
  src/components/MainHeader/MainHeaderTab/MainHeaderTab.style.ts
  src/components/MainHeader/MainHeaderTab/MainHeaderTab.tsx
  src/pages/Home/Home.tsx
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBest/components/BookItem/BookItem.style.ts
  src/pages/HomeBest/components/BookItem/BookItem.tsx
  src/pages/HomeBest/utils/getRankBadgeStyle.ts
Labels: 🛠️ Feature, 🌵 수정

#46 [feat] TabMenu 컴포넌트
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/TabMenu/TabButton.style.ts
  src/pages/HomeBestDetail/TabMenu/TabButton.tsx
  src/pages/HomeBestDetail/TabMenu/TabMenu.style.ts
  src/pages/HomeBestDetail/TabMenu/TabMenu.tsx
Labels: 🛠️ Feature, 🌼 새봄

#43 [feat] homebest 페이지 상단 카테고리, 메뉴 버튼 구현
  src/assets/icons/svg/ic_online.svg
  src/assets/icons/svg/ic_person.svg
  src/assets/icons/svg/ic_readtime.svg
  src/assets/icons/svg/ic_store.svg
  src/assets/icons/svg/ic_total.svg
  src/assets/icons/svg/ic_view.svg
  src/components/MainHeader/MainHeader.style.ts
  src/components/MainHeader/MainHeader.tsx
  src/pages/HomeBest/HomeBest.constants.ts
  src/pages/HomeBest/HomeBest.style.ts
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBest/components/BookItem/BookItem.style.ts
  src/pages/HomeBest/components/CategoryButton/CategoryButton.style.ts
  src/pages/HomeBest/components/CategoryButton/CategoryButton.tsx
  src/pages/HomeBest/components/MenuButton/MenuButton.style.ts
  src/pages/HomeBest/components/MenuButton/MenuButton.tsx
  src/pages/HomeBest/mockBooks.ts
Labels: 🛠️ Feature, 🌵 수정

#47 [feat] Review Card 컴포넌트 생성
  src/assets/icons/svg/ic_view_detail.svg
  src/components/HorizontalScroll/HorizontalScroll.style.ts
  src/components/HorizontalScroll/HorizontalScroll.tsx
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/components/elements/BookMeta/BookMeta.style.ts
  src/pages/HomeBestDetail/components/elements/BookMeta/BookMeta.tsx
  src/pages/HomeBestDetail/components/elements/EmotionBar/EmotionBar.style.ts
  src/pages/HomeBestDetail/components/elements/EmotionBar/EmotionBar.tsx
  src/pages/HomeBestDetail/components/elements/RatingBar/RatingBar.style.ts
  src/pages/HomeBestDetail/components/elements/RatingBar/RatingBar.tsx
  src/pages/HomeBestDetail/components/elements/ReviewCard/ReviewCard.style.ts
  src/pages/HomeBestDetail/components/elements/ReviewCard/ReviewCard.tsx
  src/pages/HomeBestDetail/components/elements/StarRating/StarRating.style.ts
  src/pages/HomeBestDetail/components/elements/StarRating/StarRating.tsx
  src/pages/HomeBestDetail/components/elements/TabMenu/TabButton.style.ts
  src/pages/HomeBestDetail/components/elements/TabMenu/TabButton.tsx
  src/pages/HomeBestDetail/components/elements/TabMenu/TabMenu.style.ts
  src/pages/HomeBestDetail/components/elements/TabMenu/TabMenu.tsx
  src/pages/HomeBestDetail/components/sections/AuthorInfo/index.tsx
  src/pages/HomeBestDetail/components/sections/BookDescription/index.tsx
  src/pages/HomeBestDetail/components/sections/BookReview/BookReivew.style.ts
  src/pages/HomeBestDetail/components/sections/BookReview/BookReview.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/index.tsx
  src/sampleData/ratingData.ts
  src/sampleData/reviewData.ts
  src/types/reviewTypes.ts
Labels: 🛠️ Feature, 🌼 새봄

#37 [feat] 공통 컴포넌트: 레이아웃 별 하단 네비게이션 바 및 플로팅 버튼 구현
  src/assets/icons/index.ts
  src/assets/icons/svg/ic_home_green.svg
  src/components/BottomNav/CartBottomNav.style.ts
  src/components/BottomNav/CartBottomNav.tsx
  src/components/BottomNav/DetailBottomNav.style.ts
  src/components/BottomNav/DetailBottomNav.tsx
  src/components/BottomNav/HomeBottomNav.style.ts
  src/components/BottomNav/HomeBottomNav.tsx
  src/components/Floater/Floater.style.ts
  src/components/Floater/Floater.tsx
  src/pages/Home/Home.tsx
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/routes/routePath.ts
Labels: 🛠️ Feature, ☃️ 승우

#61 [feat] 섹션 컴포넌트: BookSummary
  src/assets/img/im_book_main.png
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/components/elements/TabMenu/TabMenu.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/BookDetail.style.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/BookDetail.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/BookSummary.style.ts
  src/pages/HomeBestDetail/components/sections/BookSummary/BookSummary.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/ProductDetail.style.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/ProductDetail.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/index.tsx
  src/sampleData/bookData.ts
  src/styles/sharedStyles.ts
Labels: 🛠️ Feature, 🌼 새봄

#62 [feat] 섹션 컴포넌트: BookDescription
  src/assets/img/im_book_description.png
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/components/sections/BookDescription/BookDescription.style.ts
  src/pages/HomeBestDetail/components/sections/BookDescription/BookDescription.tsx
  src/pages/HomeBestDetail/components/sections/BookDescription/index.tsx
Labels: 🛠️ Feature, 🌼 새봄

#45 [feat] homebestdetail 페이지 하단 3영역 퍼블리싱
  .gitignore
  src/assets/img/.gitkeep
  src/assets/img/eventImage1.jpg
  src/assets/img/eventImage2.jpg
  src/assets/img/keywordImage1.jpg
  src/assets/img/keywordImage2.jpg
  src/assets/img/keywordImage3.jpg
  src/assets/img/keywordImage4.jpg
  src/components/Card/Card.tsx
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBest/components/BookItem/BookItem.tsx
  src/pages/HomeBestDetail/EventSection/EventCard/EventCard.style.ts
  src/pages/HomeBestDetail/EventSection/EventCard/EventCard.tsx
  src/pages/HomeBestDetail/EventSection/EventSection.constants.ts
  src/pages/HomeBestDetail/EventSection/EventSection.style.ts
  src/pages/HomeBestDetail/EventSection/EventSection.tsx
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/KeywordSection/FilterButton/FilterButton.style.ts
  src/pages/HomeBestDetail/KeywordSection/FilterButton/FilterButton.tsx
  src/pages/HomeBestDetail/KeywordSection/KeywordSection.constants.ts
  src/pages/HomeBestDetail/KeywordSection/KeywordSection.style.ts
  src/pages/HomeBestDetail/KeywordSection/KeywordSection.tsx
  src/pages/HomeBestDetail/NoticeSection/NoticeSection.style.ts
  src/pages/HomeBestDetail/NoticeSection/NoticeSection.tsx
  src/types/cardTypes.ts
Labels: 🛠️ Feature, 🌵 수정

#60 [feat] homebest 페이지 퍼블리싱 완료 및 mainheader sticky로 상단 고정
  src/components/MainHeader/MainHeader.style.ts
  src/components/MainHeader/MainHeader.tsx
  src/pages/HomeBest/HomeBest.style.ts
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBest/components/BookItem/BookItem.tsx
  src/pages/HomeBest/mockBooks.ts
  src/pages/HomeBest/types/book.ts
  src/pages/HomeBest/utils/addBookInfo.ts
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/components/elements/TabMenu/TabMenu.tsx
  src/pages/HomeBestDetail/components/sections/EventSection/EventCard/EventCard.style.ts
  src/pages/HomeBestDetail/components/sections/EventSection/EventCard/EventCard.tsx
  src/pages/HomeBestDetail/components/sections/EventSection/EventSection.constants.ts
  src/pages/HomeBestDetail/components/sections/EventSection/EventSection.style.ts
  src/pages/HomeBestDetail/components/sections/EventSection/EventSection.tsx
  src/pages/HomeBestDetail/components/sections/KeywordSection/FilterButton/FilterButton.style.ts
  src/pages/HomeBestDetail/components/sections/KeywordSection/FilterButton/FilterButton.tsx
  src/pages/HomeBestDetail/components/sections/KeywordSection/KeywordSection.constants.ts
  src/pages/HomeBestDetail/components/sections/KeywordSection/KeywordSection.style.ts
  src/pages/HomeBestDetail/components/sections/KeywordSection/KeywordSection.tsx
  src/pages/HomeBestDetail/components/sections/NoticeSection/NoticeSection.style.ts
  src/pages/HomeBestDetail/components/sections/NoticeSection/NoticeSection.tsx
  src/pages/HomeBestDetailCart/FourthCartView/ForthCartView.tsx
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
Labels: 🛠️ Feature, 🌵 수정

#72 [fix] 푸터 컴포넌트 수정
  src/components/Footer/Footer.style.ts
  src/components/Footer/Footer.tsx
Labels: 🌵 수정, 🔧 Fix

#74 [chore] zindex theme에 추가
  src/styles/theme.ts
Labels: 💬 Chore, 🌵 수정

#75 [feat] home best 페이지 api 연결
  src/apis/homeBest/axios.ts
  src/apis/homeBest/queries.ts
  src/components/MainHeader/MainHeader.style.ts
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBest/components/BookItem/BookItem.style.ts
  src/pages/HomeBest/components/BookItem/BookItem.tsx
  src/pages/HomeBest/mockBooks.ts
  src/pages/HomeBest/utils/addBookInfo.ts
  src/routes/routePath.ts
  src/types/HomeBestResponseTypes.ts
Labels: 🛠️ Feature, 🌵 수정

#76 [feat] homebestdetailcart페이지 퍼블리싱 완료
  src/assets/img/img_foru1.png
  src/assets/img/img_foru2.png
  src/assets/img/img_foru3.png
  src/assets/img/img_foru4.png
  src/assets/img/img_foru5.png
  src/assets/img/img_need1.png
  src/assets/img/img_need2.png
  src/assets/img/img_need3.png
  src/assets/img/img_need4.png
  src/assets/img/img_need5.png
  src/assets/img/img_preference1.png
  src/assets/img/img_preference2.png
  src/assets/img/img_preference3.png
  src/assets/img/img_preference4.png
  src/assets/img/img_preference5.png
  src/components/Floater/Floater.style.ts
  src/components/Floater/Floater.tsx
  src/pages/HomeBestDetailCart/FirstCartView/FirstCartView.tsx
  src/pages/HomeBestDetailCart/FourthCartView/FourthCartView.style.ts
  src/pages/HomeBestDetailCart/HomeBestDetailCart.style.ts
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/pages/HomeBestDetailCart/SecondCartView/SecondCartView.style.ts
  src/pages/HomeBestDetailCart/SecondCartView/SecondCartView.tsx
  src/pages/HomeBestDetailCart/ThirdCartView/ThirdCartView.style.ts
  src/pages/HomeBestDetailCart/ThirdCartView/ThirdCartView.tsx
  src/pages/HomeBestDetailCart/components/CartCard/CartCard.style.ts
  src/pages/HomeBestDetailCart/components/CartCard/CartCard.tsx
  src/types/cardTypes.ts
Labels: 🛠️ Feature, ☃️ 승우

#81 [feat] Layout에 ScrollRestoration 추가 및 zIndex theme 사용으로 모두 변경
  src/components/BottomNav/CartBottomNav.style.ts
  src/components/BottomNav/DetailBottomNav.style.ts
  src/components/BottomNav/HomeBottomNav.style.ts
  src/components/Floater/Floater.style.ts
  src/components/MainHeader/MainHeader.style.ts
  src/pages/ButtonChipTestPage.tsx
  src/pages/HomeBestDetail/components/elements/EmotionBar/EmotionBar.style.ts
  src/pages/HomeBestDetail/components/sections/BookDescription/BookDescription.style.ts
  src/pages/HomeBestDetailCart/HomeBestDetailCart.style.ts
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/pages/HomeBestDetailCart/components/CartCard/CartCard.style.ts
  src/pages/HomeBestDetailCart/components/CartCard/CartCard.tsx
  src/routes/Layout.tsx
  src/routes/pageRoutes.tsx
  src/routes/routePath.ts
Labels: 🛠️ Feature, 🌵 수정

#78 [feat] 리뷰 API 연결
  .gitignore
  src/apis/homeBestDetail/axios.ts
  src/apis/homeBestDetail/queries.ts
  src/pages/HomeBestDetail/components/elements/ReviewCard/ReviewCard.style.ts
  src/pages/HomeBestDetail/components/elements/ReviewCard/ReviewCard.tsx
  src/pages/HomeBestDetail/components/elements/TabMenu/TabMenu.tsx
  src/pages/HomeBestDetail/components/sections/BookReview/BookReview.tsx
  src/types/reviewResponseTypes.ts
  src/types/reviewTypes.ts
  src/utils/constants/apiURL.ts
  src/utils/constants/queryKey.ts
  src/utils/scrollToSection.ts
  src/utils/useBookId.ts
Labels: 🛠️ Feature, 🌼 새봄

#83 [feat] autoSync 파일 추가
  .github/workflows/autoSync.yml
Labels: 🌵 수정, 🔗 CI/CD

#68 [feat] Home 카테고리 컴포넌트 구현
  src/assets/icons/svg/ic_funding.svg
  src/assets/icons/svg/ic_mission.svg
  src/assets/icons/svg/ic_sale.svg
  src/assets/icons/svg/ic_ticket.svg
  src/assets/img/home_banner.png
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/CategoryButton/CategoryButton.styles.ts
  src/pages/Home/components/CategoryButton/CategoryButton.tsx
Labels: 🛠️ Feature, 🌟 혜성

#94 Update README.md
  README.md
Labels: 💬 Chore, 🌵 수정

#95 [fix] home best 페이지 일부 수정
  src/pages/HomeBest/components/BookItem/BookItem.tsx
  src/pages/HomeBest/components/MenuButton/MenuButton.style.ts
Labels: 🌵 수정, 🔧 Fix

#82 [feat] home best 컴포넌트 구현
  src/apis/home/axios.ts
  src/apis/home/queries.ts
  src/assets/icons/index.ts
  src/assets/icons/svg/ic_pause.svg
  src/assets/img/home_ad1.jpg
  src/assets/img/home_ad2.jpg
  src/assets/img/home_ad3.jpg
  src/assets/img/home_ad4.jpg
  src/assets/img/home_best_1.jpg
  src/assets/img/home_best_2.jpg
  src/assets/img/home_best_3.jpg
  src/assets/img/home_best_4.jpg
  src/assets/img/home_best_5.jpg
  src/assets/img/home_find1.jpg
  src/assets/img/home_find2.jpg
  src/assets/img/home_find3.jpg
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/BestBookList/BestBookList.styles.ts
  src/pages/Home/components/BestBookList/BestBookList.tsx
  src/pages/Home/components/CategoryButton/CategoryButton.tsx
  src/types/TopBookResponseType.ts
Labels: 🛠️ Feature, 🌟 혜성

#104 [feat] bookdetail API 연결
  src/apis/homeBestDetail/axios.ts
  src/apis/homeBestDetail/queries.ts
  src/pages/HomeBest/HomeBest.tsx
  src/pages/HomeBestDetail/HomeBestDetail.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/BookDetail.style.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/BookDetail.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/ProductDetail.tsx
  src/types/bookDetailTypes.ts
Labels: 🛠️ Feature, ☃️ 승우

#96 [Feat] home의 today pick 컴포넌트 구현
  src/assets/img/img_todaybook1.png
  src/assets/img/img_todaybook2.png
  src/assets/img/img_todaybook3.png
  src/pages/Home/components/TodayPick/TodayPick.style.ts
  src/pages/Home/components/TodayPick/TodayPick.tsx
Labels: 🛠️ Feature, 🌟 혜성

#97 [Feat] home publisher pick 컴포넌트 구현
  src/assets/img/img_recommend1.png
  src/assets/img/img_recommend2.png
  src/assets/img/img_recommend3.png
  src/pages/Home/components/PublisherPick/PublisherPick.style.ts
  src/pages/Home/components/PublisherPick/PublisherPick.tsx
Labels: 🛠️ Feature, 🌟 혜성

#98 [Feat] home md pick 컴포넌트 구현
  src/assets/img/img_md1.png
  src/assets/img/img_md2.png
  src/assets/img/img_md3.png
  src/pages/Home/components/MdPick/MdPick.style.ts
  src/pages/Home/components/MdPick/MdPick.tsx
Labels: 🛠️ Feature, 🌟 혜성

#100 [Feat] home 페이지의 ai pick 컴포넌트 구현
  src/assets/img/img_ai1.png
  src/assets/img/img_ai2.png
  src/assets/img/img_ai3.png
  src/assets/img/img_ai4.png
  src/pages/Home/components/AiPick/AiPick.style.ts
  src/pages/Home/components/AiPick/AiPick.tsx
Labels: 🛠️ Feature, 🌟 혜성

#101 [Feat] home 페이지의 교보 only 컴포넌트 구현
  src/assets/img/img_meet1.png
  src/assets/img/img_meet2.png
  src/assets/img/img_meet3.png
  src/pages/Home/components/Only/Only.style.ts
  src/pages/Home/components/Only/Only.tsx
Labels: 🛠️ Feature, 🌟 혜성

#102 [Feat] home 페이지의 casting 컴포넌트 구현
  src/assets/img/img_casting1.png
  src/assets/img/img_casting2.png
  src/assets/img/img_casting3.png
  src/pages/Home/components/BestBookList/BestBookList.style.ts
  src/pages/Home/components/BestBookList/BestBookList.tsx
  src/pages/Home/components/Casting/Casting.style.ts
  src/pages/Home/components/Casting/Casting.tsx
  src/pages/Home/components/CategoryButton/CategoryButton.style.ts
  src/pages/Home/components/CategoryButton/CategoryButton.tsx
Labels: 🛠️ Feature, 🌟 혜성

#103 [Feat] home 페이지의 event 배너 컴포넌트 구현
  src/assets/img/_img_event1.png
  src/assets/img/_img_event2.png
  src/pages/Home/components/Event/Event.style.ts
  src/pages/Home/components/Event/Event.tsx
Labels: 🛠️ Feature, 🌟 혜성

#109 [feat] HomeBestDetailCart 페이지 Api 연동
  src/components/BottomNav/CartBottomNav.tsx
  src/components/BottomNav/DetailBottomNav.tsx
  src/pages/HomeBestDetailCart/FirstCartView/FirstCartView.style.ts
  src/pages/HomeBestDetailCart/FirstCartView/FirstCartView.tsx
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/pages/HomeBestDetailCart/ThirdCartView/ThirdCartView.tsx
  src/routes/routePath.ts
Labels: 🛠️ Feature, ☃️ 승우

#111 [fix] update 1
  index.html
  public/svg/.gitkeep
  src/assets/icons/index.ts
  src/assets/icons/svg/ic_banner_ad2.svg
  src/assets/icons/svg/ic_banner_ad3.svg
  src/assets/icons/svg/ic_banner_ad4.svg
  src/assets/icons/svg/ic_funding.svg
  src/assets/icons/svg/ic_home_best_store.svg
  src/assets/icons/svg/ic_mission.svg
  src/assets/icons/svg/ic_sale.svg
  src/assets/icons/svg/ic_store.svg
  src/assets/icons/svg/ic_ticket.svg
  src/assets/img/banner1.jpg
  src/assets/img/home_ad1.jpg
  src/assets/img/home_ad2.jpg
  src/assets/img/home_ad3.jpg
  src/assets/img/home_ad4.jpg
  src/components/DetailHeader/DetailHeader.tsx
  src/components/MainHeader/MainHeader.style.ts
  src/pages/Home/Home.style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/components/Ad/AdCard.style.ts
  src/pages/Home/components/Ad/AdCard.tsx
  src/pages/Home/components/AiPick/AiPick.style.ts
  src/pages/Home/components/BestBookList/BestBookList.style.ts
  src/pages/Home/components/BestBookList/BestBookList.tsx
  src/pages/Home/components/Casting/Casting.style.ts
  src/pages/Home/components/Casting/Casting.tsx
  src/pages/Home/components/CategoryButton/CategoryButton.tsx
  src/pages/Home/components/Event/Event.style.ts
  src/pages/Home/components/Event/Event.tsx
  src/pages/Home/components/Find/Find.style.ts
  src/pages/Home/components/MdPick/MdPick.style.ts
  src/pages/Home/components/MdPick/MdPick.tsx
  src/pages/Home/components/Only/Only.style.ts
  src/pages/Home/components/PublisherPick/PublisherPick.style.ts
  src/pages/Home/components/PublisherPick/PublisherPick.tsx
  src/pages/Home/components/TodayPick/TodayPick.style.ts
  src/pages/Home/components/TodayPick/TodayPick.tsx
  src/pages/HomeBest/HomeBest.constants.ts
  src/pages/HomeBestDetail/components/sections/BookSummary/BookDetail.style.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/BookDetail.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/ProductDetail.style.tsx
  src/pages/HomeBestDetail/components/sections/BookSummary/ProductDetail.tsx
  src/pages/HomeBestDetailCart/FirstCartView/FirstCartView.tsx
  src/pages/HomeBestDetailCart/FourthCartView/FourthCartView.style.ts
  src/pages/HomeBestDetailCart/HomeBestDetailCart.style.ts
  src/pages/HomeBestDetailCart/HomeBestDetailCart.tsx
  src/pages/HomeBestDetailCart/SecondCartView/SecondCartView.style.ts
  src/pages/HomeBestDetailCart/SecondCartView/SecondCartView.tsx
  src/pages/HomeBestDetailCart/ThirdCartView/ThirdCartView.style.ts
  src/pages/HomeBestDetailCart/ThirdCartView/ThirdCartView.tsx
  vercel.json
Labels: 🛠️ Feature, 🌵 수정, 🔧 Fix
